export enum ScreensURL {
    Button = 'button',
    Toast = 'toast',
    Form = 'form',
    Tabel = 'tabel',
    Calendar = 'calendar',
    Checkbox = 'checkbox',
    FileUploader = 'file-uploader',
    PickList = 'pick-list',
    Tabs = 'tabs',
    Paginator = 'paginator',
    Image = 'image',
    Galleria = 'galleria',
    Carousel = 'carousel',
    Otp = 'otp',
    Stepper = 'stepper',
    DataView = 'data-view',
    RadioButton = 'radio-button',
    ColorPicker = 'color-picker',
    Accordion = 'accordion',
    ContextMenu = 'context-menu',
    Menu = 'menu',
    Rating = 'rating',
    AugmentedReality = 'augmented-reality',
    Breadcrumb = 'breadcrumb'
}